basePath: /
definitions:
  app.SwaggerUpdateTurnRequest:
    properties:
      turn_type:
        type: string
    type: object
  ds.Card:
    properties:
      description:
        maxLength: 200
        type: string
      image_url:
        type: string
      name:
        maxLength: 50
        type: string
      needfood:
        type: integer
      type:
        maxLength: 50
        type: string
      uuid:
        type: string
    required:
    - description
    - name
    - needfood
    - type
    type: object
  schemes.AddToTurnResp:
    properties:
      card_count:
        type: integer
    type: object
  schemes.AllCardsResponse:
    properties:
      cards:
        items:
          $ref: '#/definitions/ds.Card'
        type: array
    type: object
  schemes.AllTurnsResponse:
    properties:
      turns:
        items:
          $ref: '#/definitions/schemes.TurnOutput'
        type: array
    type: object
  schemes.GetAllCardsResponse:
    properties:
      cards:
        items:
          $ref: '#/definitions/ds.Card'
        type: array
      draft_turn:
        $ref: '#/definitions/schemes.TurnShort'
    type: object
  schemes.LoginReq:
    properties:
      login:
        maxLength: 30
        type: string
      password:
        maxLength: 30
        type: string
    required:
    - login
    - password
    type: object
  schemes.RegisterReq:
    properties:
      login:
        maxLength: 30
        type: string
      password:
        maxLength: 30
        type: string
    required:
    - login
    - password
    type: object
  schemes.RegisterResp:
    properties:
      ok:
        type: boolean
    type: object
  schemes.SwaggerLoginResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  schemes.TurnOutput:
    properties:
      completion_date:
        type: string
      creation_date:
        type: string
      customer:
        type: string
      formation_date:
        type: string
      moderator:
        type: string
      sending_status:
        type: string
      status:
        type: string
      takefood:
        type: integer
      turn_type:
        type: string
      uuid:
        type: string
    type: object
  schemes.TurnResponse:
    properties:
      cards:
        items:
          $ref: '#/definitions/ds.Card'
        type: array
      turn:
        $ref: '#/definitions/schemes.TurnOutput'
    type: object
  schemes.TurnShort:
    properties:
      card_count:
        type: integer
      uuid:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  title: Electronic notifications
  version: "1.0"
paths:
  /api/cards:
    get:
      description: Возвращает всех доуступных получателей с опциональной фильтрацией
        по ФИО
      parameters:
      - description: ФИО для фильтрации
        in: query
        name: fio
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.GetAllCardsResponse'
      summary: Получить всех получателей
      tags:
      - Получатели
    post:
      consumes:
      - multipart/form-data
      description: Добавить нового получателя
      parameters:
      - description: Изображение получателя
        in: formData
        name: image
        type: file
      - description: ФИО
        in: formData
        name: fio
        required: true
        type: string
      - description: Почта
        in: formData
        name: email
        required: true
        type: string
      - description: Возраст
        in: formData
        name: age
        required: true
        type: integer
      - description: Адрес
        in: formData
        name: adress
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Добавить получателя
      tags:
      - Получатели
  /api/cards/{id}:
    delete:
      description: Удаляет получателя по id
      parameters:
      - description: id получателя
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Удалить получателя
      tags:
      - Получатели
    get:
      description: Возвращает более подробную информацию об одном получателе
      parameters:
      - description: id получателя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Card'
      summary: Получить одного получателя
      tags:
      - Получатели
    put:
      consumes:
      - multipart/form-data
      description: Изменить данные полей о получателе
      parameters:
      - description: Идентификатор получателя
        in: path
        name: id
        required: true
        type: string
      - description: ФИО
        in: formData
        name: fio
        type: string
      - description: Почта
        in: formData
        name: email
        type: string
      - description: Возраст
        in: formData
        name: age
        type: integer
      - description: Изображение получателя
        in: formData
        name: image
        type: file
      - description: Адрес
        in: formData
        name: adress
        type: string
      produces:
      - application/json
      responses: {}
      summary: Изменить получателя
      tags:
      - Получатели
  /api/cards/{id}/add_to_turn:
    post:
      description: Добавить выбранного получателя в черновик уведомления
      parameters:
      - description: id получателя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.AddToTurnResp'
      summary: Добавить в уведомление
      tags:
      - Получатели
  /api/turns:
    delete:
      description: Удаляет черновое карту
      responses:
        "200":
          description: OK
      summary: Удалить черновое карту
      tags:
      - Ходы
    get:
      description: Возвращает все ходы с фильтрацией по статусу и дате формирования
      parameters:
      - description: статус ходы
        in: query
        name: status
        type: string
      - description: начальная дата формирования
        in: query
        name: formation_date_start
        type: string
      - description: конечная дата формирвания
        in: query
        name: formation_date_end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.AllTurnsResponse'
      summary: Получить все ходы
      tags:
      - Ходы
    put:
      description: Позволяет изменить тип чернового ходы и возвращает обновлённые
        данные
      parameters:
      - description: Тип ходы
        in: body
        name: turn_type
        required: true
        schema:
          $ref: '#/definitions/app.SwaggerUpdateTurnRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.TurnOutput'
      summary: Указать тип ходы
      tags:
      - Ходы
  /api/turns/{id}:
    get:
      description: Возвращает подробную информацию об ходы и его типе
      parameters:
      - description: id ходы
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.TurnResponse'
      summary: Получить одно карту
      tags:
      - Ходы
  /api/turns/{id}/moderator_confirm:
    put:
      description: Подтвердить или отменить карту модератором
      parameters:
      - description: id ходы
        in: path
        name: id
        required: true
        type: string
      - description: подтвердить
        in: body
        name: confirm
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.TurnOutput'
      summary: Подтвердить карту
      tags:
      - Ходы
  /api/turns/delete_recipient/{id}:
    delete:
      description: Удалить получателя из черновово ходы
      parameters:
      - description: id получателя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.AllCardsResponse'
      summary: Удалить получателя из черновово ходы
      tags:
      - Ходы
  /api/turns/user_confirm:
    put:
      description: Сформировать карту пользователем
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.TurnOutput'
      summary: Сформировать ход
      tags:
      - Ходы
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя по логиню, паролю и отдаёт jwt токен для
        дальнейших запросов
      parameters:
      - description: login and password
        in: body
        name: user_credentials
        required: true
        schema:
          $ref: '#/definitions/schemes.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.SwaggerLoginResp'
      summary: Авторизация
      tags:
      - Авторизация
  /api/user/logout:
    post:
      consumes:
      - application/json
      description: Выход из аккаунта
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Выйти из аккаунта
      tags:
      - Авторизация
  /api/user/sign_up:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя
      parameters:
      - description: login and password
        in: body
        name: user_credentials
        required: true
        schema:
          $ref: '#/definitions/schemes.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.RegisterResp'
      summary: Регистрация
      tags:
      - Авторизация
schemes:
- http
swagger: "2.0"
